config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: %i(show)
  resources :journeys, only: %i(new create)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journey.rb
class Journey < ApplicationRecord

  validates :origin_address, presence: true
  validates :destination_address, presence: true
  validates :arrival_time, presence: true
  validates :duration, presence: true, unless: Proc.new { |j| j.primary }

  before_save :geocode_origin_address
  before_save :geocode_destination_address

  belongs_to :user

  private

  def geocode_origin_address
    if origin_address_changed?
      geocoded = Geocoder.search(origin_address).first
      if geocoded
        self.origin_latitude = geocoded.latitude
        self.origin_longitude = geocoded.longitude
      end
    end
  end

  def geocode_destination_address
    if destination_address_changed?
      geocoded = Geocoder.search(destination_address).first
      if geocoded
        self.destination_latitude = geocoded.latitude
        self.destination_longitude = geocoded.longitude
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :journeys

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController

  def new
    @journey = Journey.new
    @journey.primary = true if current_user.journeys.empty?
  end

  def create
    @journey = Journey.new(journey_params)
    @journey.primary = true if current_user.journeys.empty?
    @journey.user = current_user
    if @journey.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def journey_params
    params.require(:journey).permit(:origin_address, :destination_address, :arrival_time,
                                    :car, :bicycle, :public_transport, :duration)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @journey = @user.journeys.where.not(origin_latitude: nil, origin_longitude: nil,
                                        destination_longitude: nil, destination_longitude: nil).first
    @markers = [
                 {
                   lat: @journey.origin_latitude,
                   lng: @journey.origin_longitude
                 },
                 {
                   lat: @journey.destination_latitude,
                   lng: @journey.destination_longitude
                 }
               ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/journeys/new.html.erb
<div class="container pt-5 mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-8 col-md-6">
      <h2 class="mb-4">Tell <strong>Freddy</strong> about your daily commute.</h2>
      <%= simple_form_for @journey do |f| %>
        <%= f.input :origin_address, placeholder: "Where do you start from?", label: false %>
        <%= f.input :destination_address, placeholder: "Where do you have to go to?", label: false %>
        <%= f.input :arrival_time %>

        <h3>How can you get there?</h3>
        <%= f.input :car %>
        <%= f.input :bicycle %>
        <%= f.input :public_transport %>
        <% unless @journey.primary %>
          <%= f.input :duration %>
        <% end %>
        <%= f.submit class: "btn btn-freddy-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Freddy - Traffic based notifications for your daily commute</title>
    <%= favicon_link_tag "favicon.png" %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="map-bg">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-8">
        <div class="home-banner">
          <h1>Let <strong>Freddy</strong> tell you when to get out of bed!</h1>
          <p>Freddy is a traffic based notification system that will help you get to work on time! All you have to do is tell Freddy what point A & B are, what time you have to be in and Freddy tell you each morning at what time you have to get out of the house.</p>
          <% if user_signed_in? %>
            <%= link_to "Setup your journey", new_journey_path, class: "btn btn-freddy-primary btn-lg mt-4" %>
            <%#= link_to "Go to your profile", user_path(current_user), class: "btn btn-freddy-primary btn-lg mt-4" %>
          <% else %>
            <%= link_to "Give it a try?", new_user_session_path, class: "btn btn-freddy-primary btn-lg mt-4"  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-freddy fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-freddy-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <div class="navbar-freddy-navigation">
    <!-- Add links here if needed -->
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
></div>

<%= content_for(:after_js) do %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_pack_tag "map" %>
<% end %>